require_relative '../node_modules/react-native-macos/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

prepare_react_native_project!

target 'AudioBookConverter-macOS' do
  platform :macos, '11.0'
  use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => '../node_modules/react-native-macos',
    :hermes_enabled => false,
    :fabric_enabled => ENV['RCT_NEW_ARCH_ENABLED'] == '1',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(installer)

    # Work around Apple clang + fmt consteval failures in RCT-Folly/fmt
    # (e.g. "Call to consteval function ... is not a constant expression").
    installer.pods_project.targets.each do |target|
      next unless ['fmt', 'RCT-Folly'].include?(target.name)

      target.build_configurations.each do |config|
        defs = config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] || ['$(inherited)']
        defs = [defs] unless defs.is_a?(Array)
        defs = defs.reject do |d|
          d.start_with?('FMT_USE_CONSTEXPR=') ||
            d.start_with?('FMT_USE_CONSTEVAL=') ||
            d.start_with?('FMT_USE_NONTYPE_TEMPLATE_ARGS=')
        end
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = defs

        if target.name == 'fmt'
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
          cxx_flags = config.build_settings['OTHER_CPLUSPLUSFLAGS'] || ['$(inherited)']
          cxx_flags = [cxx_flags] unless cxx_flags.is_a?(Array)
          cxx_flags << '-Wno-invalid-constexpr' unless cxx_flags.include?('-Wno-invalid-constexpr')
          cxx_flags << '-Wno-macro-redefined' unless cxx_flags.include?('-Wno-macro-redefined')
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] = cxx_flags
        end
      end
    end
  end
end
